import { Geist, Geist_Mono,Outfit,Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const outfit=Outfit({subsets:['latin']})

export const metadata = {
  title: "InteriorAI Studio",
  description: "Generated by InteriorAI Studio",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={outfit.className}
      >
        <Provider>
        {children}
        </Provider>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
